version: '3.13'
services: 
    rabbitmq:
        container_name: "rabbitmq"
        image: rabbitmq:3.13-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
          #RabbitMq interface
          - '5672:5672'
          #Web interface
          - '15672:15672'